backend:
  name: github
  repo: mohan2020/w2hsite # Path to your Github repository
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "site/static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "casestudies" # Used in routes, e.g., /admin/collections/blog
    label: "Case Study Highlights" # Used in the UI
    folder: "site/content/casestudies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the case study
      - {label: "Publish Date", name: "date", widget: "datetime"} # date of publication / creation
      - {label: "Study Type", name: "area", widget: "string"} # Clinical or research area
      - {label: "Clinical Domain", name: "subdomain", widget: "string"} # Specific clinical or ops area
      - {label: "PI Name", name: "name", widget: "string"} #Author Name
      - {label: "PI image", name: "image", widget: "image"} # pic image
      - {label: "Role", name: "role", widget: "string"} #Role in study      
      - {label: "Co-PI Name", name: "name", widget: "string"} #Author Name
      - {label: "Co-PI image", name: "image", widget: "image"} # pic image
      - {label: "Role", name: "role", widget: "string"} #Role in study      
      - {label: "Other Name", name: "name", widget: "string"} #Author Name
      - {label: "Other image", name: "image", widget: "image"} # pic image
      - {label: "Role", name: "role", widget: "string"} #Role in study
      - {label: "Summary", name: "summary", widget: "string"} # summary of the study
      - {label: "Outcome 1", name: "result", widget: "string"} #outcome 1
      - {label: "Outcome 2", name: "result", widget: "string"} #outcome 2      
      - {label: "Body", name: "body", widget: "markdown"} #body of the case study
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Company blog" # Used in the UI
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the blog post
      - {label: "Publish Date", name: "date", widget: "datetime"} # date of publication / creation
      - {label: "Summary", name: "summary", widget: "string"} # summary of the post
      - {label: "Splash image", name: "image", widget: "image"} # background image
      - {label: "Author Name", name: "authorname", widget: "string"} #Author Name
      - {label: "Author image", name: "authorimage", widget: "image"} # background image
      - {label: "Body", name: "body", widget: "markdown"} #body of the case study
  - name: "enggblog" # Used in routes, e.g., /admin/collections/blog
    label: "Product & Engineering blog" # Used in the UI
    folder: "site/content/enggblog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the blog post
      - {label: "Publish Date", name: "date", widget: "datetime"} # date of publication / creation
      - {label: "Summary", name: "summary", widget: "string"} # summary of the post
      - {label: "Splash image", name: "image", widget: "image"} # background image
      - {label: "Author Name", name: "authorname", widget: "string"} #Author Name
      - {label: "Author image", name: "authorimage", widget: "image"} # background image
      - {label: "Body", name: "body", widget: "markdown"} #body of the case study
  - name: "institute" # Used in routes, e.g., /admin/collections/blog
    label: "Institute Posts" # Used in the UI
    folder: "site/content/institute" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the blog post
      - {label: "Publish Date", name: "date", widget: "datetime"} # date of publication / creation
      - {label: "Summary", name: "summary", widget: "string"} # summary of the post
      - {label: "Splash image", name: "image", widget: "image"} # background image
      - {label: "Author Name", name: "authorname", widget: "string"} #Author Name
      - {label: "Author image", name: "authorimage", widget: "image"} # background image
      - {label: "Body", name: "body", widget: "markdown"} #body of the case study
  - name: "press" # Used in routes, e.g., /admin/collections/blog
    label: "Press" # Used in the UI
    folder: "site/content/press" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the blog post
      - {label: "Publish Date", name: "date", widget: "datetime"} # date of publication / creation
      - {label: "Summary", name: "summary", widget: "string"} # summary of the post
      - {label: "Splash image", name: "image", widget: "image"} # background image
      - {label: "Source", name: "source", widget: "string"} #Author Name
  - name: "publications" # Used in routes, e.g., /admin/collections/blog
    label: "Publications" # Used in the UI
    folder: "site/content/publications" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the blog post
      - {label: "Publish Date", name: "date", widget: "datetime"} # date of publication / creation
      - {label: "Summary", name: "summary", widget: "string"} # summary of the post
      - {label: "Authors", name: "authors", widget: "string"} # publication authors
      - {label: "Source", name: "source", widget: "string"} #Author Name      


