backend:
  name: github
  repo: mohan2020/w2hsite # Path to your Github repository
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "casestudies" # Used in routes, e.g., /admin/collections/blog
    label: "Case Study Highlights" # Used in the UI
    folder: "content/casestudies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #title of the case study
      - {label: "Publish Date", name: "date", widget: "datetime"} # date of publication / creation
      - {label: "Study Type", name: "area", widget: "string"} # Clinical or research area
      - {label: "Subdomain", name: "Clinical Domain", widget: "string"} # Specific clinical or ops area
      - {label: "Summary", name: "summary", widget: "string"} # summary of the study
      - {label: "Body", name: "body", widget: "markdown"} #body of the case study